#!/bin/bash

if [[ "$SOURCE_BRANCH" = "carma-develop" ]]; then
    # add -t flag to checkout.sh and update image dependencies
    sed -i "s|usdotfhwastol|usdotfhwastoldev|g; s|:[0-9]*\.[0-9]*\.[0-9]*|:develop|g" \
        Dockerfile
fi